/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.sistemaplanejago.view;

import java.awt.Color;

/**
 *
 * @author diego
 */
public class DespesaForm extends javax.swing.JDialog {

    /**
     * Creates new form DespesaForm
     */
    public DespesaForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent); //Centralizar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelCentralizador = new javax.swing.JPanel();
        panelContent = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        panelDescricao = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        fieldDescricao = new javax.swing.JTextField();
        panelValor = new javax.swing.JPanel();
        labelValor = new javax.swing.JLabel();
        fieldValor = new javax.swing.JTextField();
        labelEmail1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panelCategoria = new javax.swing.JPanel();
        labelCategoria = new javax.swing.JLabel();
        ComboBoxCategoria = new javax.swing.JComboBox<>();
        labelCentralCusto = new javax.swing.JLabel();
        ComboBoxCentralCusto = new javax.swing.JComboBox<>();
        panelDatas = new javax.swing.JPanel();
        labelDataCriacao = new javax.swing.JLabel();
        fieldDataCriacao = new javax.swing.JTextField();
        labelDataVencimento = new javax.swing.JLabel();
        fieldDataVencimento = new javax.swing.JTextField();
        panelRepeticao = new javax.swing.JPanel();
        labelRepeticao = new javax.swing.JLabel();
        ComboBoxRepeticao = new javax.swing.JComboBox<>();
        panelSalvar = new javax.swing.JPanel();
        buttonSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        panelCentralizador.setBackground(new java.awt.Color(255, 255, 255));
        panelCentralizador.setLayout(new java.awt.GridBagLayout());

        panelContent.setLayout(new java.awt.GridLayout(0, 1));

        panelTitulo.setBackground(new java.awt.Color(255, 255, 255));

        labelTitulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(97, 90, 205));
        labelTitulo.setText("Nova Despesa");
        panelTitulo.add(labelTitulo);

        panelContent.add(panelTitulo);

        panelDescricao.setBackground(new java.awt.Color(255, 255, 255));

        labelDescricao.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDescricao.setForeground(new java.awt.Color(19, 16, 71));
        labelDescricao.setText("Descrição");

        fieldDescricao.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescricao.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldDescricao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDescricaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDescricaoLayout = new javax.swing.GroupLayout(panelDescricao);
        panelDescricao.setLayout(panelDescricaoLayout);
        panelDescricaoLayout.setHorizontalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addGroup(panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldDescricao)
                    .addGroup(panelDescricaoLayout.createSequentialGroup()
                        .addComponent(labelDescricao)
                        .addGap(0, 394, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDescricaoLayout.setVerticalGroup(
            panelDescricaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDescricaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDescricao)
                .addContainerGap())
        );

        panelContent.add(panelDescricao);

        panelValor.setBackground(new java.awt.Color(255, 255, 255));

        labelValor.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelValor.setForeground(new java.awt.Color(19, 16, 71));
        labelValor.setText("Valor");

        fieldValor.setBackground(new java.awt.Color(255, 255, 255));
        fieldValor.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldValor.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldValorActionPerformed(evt);
            }
        });

        labelEmail1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelEmail1.setForeground(new java.awt.Color(19, 16, 71));
        labelEmail1.setText("Email");

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout panelValorLayout = new javax.swing.GroupLayout(panelValor);
        panelValor.setLayout(panelValorLayout);
        panelValorLayout.setHorizontalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelValorLayout.createSequentialGroup()
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelValor)
                    .addComponent(fieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelValorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelEmail1)
                        .addGap(207, 207, 207))
                    .addGroup(panelValorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelValorLayout.setVerticalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelValorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelValor)
                    .addComponent(labelEmail1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldValor)
                    .addComponent(jComboBox1))
                .addContainerGap())
        );

        panelContent.add(panelValor);

        panelCategoria.setBackground(new java.awt.Color(255, 255, 255));
        panelCategoria.setPreferredSize(new java.awt.Dimension(418, 95));

        labelCategoria.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(19, 16, 71));
        labelCategoria.setText("Categoria");

        ComboBoxCategoria.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxCategoria.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        labelCentralCusto.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelCentralCusto.setForeground(new java.awt.Color(19, 16, 71));
        labelCentralCusto.setText("Central Custo");

        ComboBoxCentralCusto.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxCentralCusto.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ComboBoxCentralCusto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout panelCategoriaLayout = new javax.swing.GroupLayout(panelCategoria);
        panelCategoria.setLayout(panelCategoriaLayout);
        panelCategoriaLayout.setHorizontalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCategoria)
                    .addComponent(ComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxCentralCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCentralCusto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCategoriaLayout.setVerticalGroup(
            panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCategoria)
                    .addComponent(labelCentralCusto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxCategoria)
                    .addComponent(ComboBoxCentralCusto, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContent.add(panelCategoria);

        panelDatas.setBackground(new java.awt.Color(255, 255, 255));

        labelDataCriacao.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDataCriacao.setForeground(new java.awt.Color(19, 16, 71));
        labelDataCriacao.setText("Data da Criação");

        fieldDataCriacao.setBackground(new java.awt.Color(255, 255, 255));
        fieldDataCriacao.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldDataCriacao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDataCriacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDataCriacaoActionPerformed(evt);
            }
        });

        labelDataVencimento.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelDataVencimento.setForeground(new java.awt.Color(19, 16, 71));
        labelDataVencimento.setText("Data de Vencimento");

        fieldDataVencimento.setBackground(new java.awt.Color(255, 255, 255));
        fieldDataVencimento.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        fieldDataVencimento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        fieldDataVencimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDataVencimentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatasLayout = new javax.swing.GroupLayout(panelDatas);
        panelDatas.setLayout(panelDatasLayout);
        panelDatasLayout.setHorizontalGroup(
            panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatasLayout.createSequentialGroup()
                .addGroup(panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelDataCriacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(fieldDataCriacao, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatasLayout.createSequentialGroup()
                        .addComponent(labelDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addGap(36, 36, 36))
                    .addGroup(panelDatasLayout.createSequentialGroup()
                        .addComponent(fieldDataVencimento)
                        .addContainerGap())))
        );
        panelDatasLayout.setVerticalGroup(
            panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatasLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDataCriacao)
                    .addComponent(labelDataVencimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldDataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(fieldDataVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelContent.add(panelDatas);

        panelRepeticao.setBackground(new java.awt.Color(255, 255, 255));
        panelRepeticao.setPreferredSize(new java.awt.Dimension(418, 95));

        labelRepeticao.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        labelRepeticao.setForeground(new java.awt.Color(19, 16, 71));
        labelRepeticao.setText("Repetição");

        ComboBoxRepeticao.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxRepeticao.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        ComboBoxRepeticao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        javax.swing.GroupLayout panelRepeticaoLayout = new javax.swing.GroupLayout(panelRepeticao);
        panelRepeticao.setLayout(panelRepeticaoLayout);
        panelRepeticaoLayout.setHorizontalGroup(
            panelRepeticaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRepeticaoLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panelRepeticaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRepeticaoLayout.createSequentialGroup()
                        .addComponent(labelRepeticao)
                        .addGap(206, 206, 206))
                    .addGroup(panelRepeticaoLayout.createSequentialGroup()
                        .addComponent(ComboBoxRepeticao, 0, 476, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        panelRepeticaoLayout.setVerticalGroup(
            panelRepeticaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRepeticaoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(labelRepeticao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxRepeticao)
                .addContainerGap())
        );

        panelContent.add(panelRepeticao);

        panelSalvar.setBackground(new java.awt.Color(255, 255, 255));

        buttonSalvar.setBackground(new java.awt.Color(5, 137, 40));
        buttonSalvar.setFont(new java.awt.Font("Roboto", 1, 20)); // NOI18N
        buttonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        buttonSalvar.setText("Salvar");
        buttonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonSalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonSalvarMouseExited(evt);
            }
        });
        buttonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSalvarLayout = new javax.swing.GroupLayout(panelSalvar);
        panelSalvar.setLayout(panelSalvarLayout);
        panelSalvarLayout.setHorizontalGroup(
            panelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalvarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSalvarLayout.setVerticalGroup(
            panelSalvarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalvarLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(buttonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelContent.add(panelSalvar);

        panelCentralizador.add(panelContent, new java.awt.GridBagConstraints());

        panelPrincipal.add(panelCentralizador, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDescricaoActionPerformed

    private void fieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldValorActionPerformed

    private void fieldDataCriacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDataCriacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDataCriacaoActionPerformed

    private void buttonSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarMouseEntered
        // TODO add your handling code here:
        buttonSalvar.setBackground(new Color(255, 165, 0));

    }//GEN-LAST:event_buttonSalvarMouseEntered

    private void buttonSalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSalvarMouseExited
        // TODO add your handling code here:
        buttonSalvar.setBackground(new Color(97, 90, 205));
    }//GEN-LAST:event_buttonSalvarMouseExited

    private void buttonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buttonSalvarActionPerformed

    private void fieldDataVencimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDataVencimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDataVencimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DespesaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DespesaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DespesaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DespesaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DespesaForm dialog = new DespesaForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCategoria;
    private javax.swing.JComboBox<String> ComboBoxCentralCusto;
    private javax.swing.JComboBox<String> ComboBoxRepeticao;
    private javax.swing.JButton buttonSalvar;
    private javax.swing.JTextField fieldDataCriacao;
    private javax.swing.JTextField fieldDataVencimento;
    private javax.swing.JTextField fieldDescricao;
    private javax.swing.JTextField fieldValor;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCentralCusto;
    private javax.swing.JLabel labelDataCriacao;
    private javax.swing.JLabel labelDataVencimento;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelRepeticao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelValor;
    private javax.swing.JPanel panelCategoria;
    private javax.swing.JPanel panelCentralizador;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelDatas;
    private javax.swing.JPanel panelDescricao;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRepeticao;
    private javax.swing.JPanel panelSalvar;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelValor;
    // End of variables declaration//GEN-END:variables
}
