/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemaplanejago.view;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Liah
 */
public class TelaRelatorios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorios.class.getName());

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
        adicionarGraficos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelNavegação = new javax.swing.JPanel();
        labelPlanejaGo = new javax.swing.JLabel();
        labelLançamentos = new javax.swing.JLabel();
        labelRelatórios = new javax.swing.JLabel();
        labelCalculadora = new javax.swing.JLabel();
        Panelicones = new javax.swing.JPanel();
        jLabelNotificação = new javax.swing.JLabel();
        jLabelUsuário = new javax.swing.JLabel();
        jPanelFiltros = new javax.swing.JPanel();
        jButtonGerar = new javax.swing.JButton();
        labelPeríodo = new javax.swing.JLabel();
        labelTipoLançamento = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        jComboBoxLançamentos = new javax.swing.JComboBox<>();
        jComboBoxPeríodo = new javax.swing.JComboBox<>();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        labelRelatóriosBlue = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavegação.setBackground(new java.awt.Color(44, 41, 102));
        panelNavegação.setPreferredSize(new java.awt.Dimension(800, 70));
        panelNavegação.setLayout(new javax.swing.BoxLayout(panelNavegação, javax.swing.BoxLayout.X_AXIS));

        labelPlanejaGo.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        labelPlanejaGo.setForeground(new java.awt.Color(255, 160, 81));
        labelPlanejaGo.setText("PlanejaGo ");
        labelPlanejaGo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        panelNavegação.add(labelPlanejaGo);

        labelLançamentos.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelLançamentos.setForeground(new java.awt.Color(255, 255, 255));
        labelLançamentos.setText("Lançamentos");
        labelLançamentos.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        labelLançamentos.setFocusable(false);
        panelNavegação.add(labelLançamentos);

        labelRelatórios.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelRelatórios.setForeground(new java.awt.Color(255, 255, 255));
        labelRelatórios.setText("Relatórios ");
        labelRelatórios.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        panelNavegação.add(labelRelatórios);

        labelCalculadora.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        labelCalculadora.setForeground(new java.awt.Color(255, 255, 255));
        labelCalculadora.setText("Calculadora");
        labelCalculadora.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 30, 0, 0));
        panelNavegação.add(labelCalculadora);

        getContentPane().add(panelNavegação, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, -1));

        Panelicones.setBackground(new java.awt.Color(44, 41, 102));
        Panelicones.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 30));
        Panelicones.setLayout(null);

        jLabelNotificação.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jr\\Saved Games\\sistema-financas\\SistemaPlanejaGo\\src\\Icons\\Imagens\\notification (2).png")); // NOI18N
        Panelicones.add(jLabelNotificação);
        jLabelNotificação.setBounds(40, 20, 30, 40);

        jLabelUsuário.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jr\\Saved Games\\sistema-financas\\SistemaPlanejaGo\\src\\Icons\\Imagens\\profile (3).png")); // NOI18N
        Panelicones.add(jLabelUsuário);
        jLabelUsuário.setBounds(80, 0, 64, 70);

        getContentPane().add(Panelicones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 0, 150, 70));

        jPanelFiltros.setBackground(new java.awt.Color(229, 229, 246));
        jPanelFiltros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 246), 2, true));
        jPanelFiltros.setForeground(new java.awt.Color(229, 229, 246));

        jButtonGerar.setBackground(new java.awt.Color(97, 90, 205));
        jButtonGerar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonGerar.setText("Gerar");
        jButtonGerar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 90, 205), 2, true));
        jButtonGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarActionPerformed(evt);
            }
        });

        labelPeríodo.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelPeríodo.setForeground(new java.awt.Color(19, 16, 71));
        labelPeríodo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPeríodo.setText("Período");
        labelPeríodo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelTipoLançamento.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelTipoLançamento.setForeground(new java.awt.Color(19, 16, 71));
        labelTipoLançamento.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTipoLançamento.setText("Tipo de Lançamento");
        labelTipoLançamento.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelCategoria.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelCategoria.setForeground(new java.awt.Color(19, 16, 71));
        labelCategoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCategoria.setText("Categoria");
        labelCategoria.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelStatus.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(19, 16, 71));
        labelStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelStatus.setText("Status");
        labelStatus.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jComboBoxLançamentos.setForeground(new java.awt.Color(19, 16, 71));
        jComboBoxLançamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Despesa", "Receita" }));
        jComboBoxLançamentos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBoxLançamentos.setMinimumSize(new java.awt.Dimension(108, 22));
        jComboBoxLançamentos.setOpaque(true);
        jComboBoxLançamentos.setPreferredSize(new java.awt.Dimension(108, 22));
        jComboBoxLançamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLançamentosActionPerformed(evt);
            }
        });

        jComboBoxPeríodo.setForeground(new java.awt.Color(19, 16, 71));
        jComboBoxPeríodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Hoje", "Esta Semana", "Este Mês", "Este Semestre" }));
        jComboBoxPeríodo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBoxPeríodo.setName(""); // NOI18N
        jComboBoxPeríodo.setOpaque(true);
        jComboBoxPeríodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPeríodoActionPerformed(evt);
            }
        });

        jComboBoxCategoria.setForeground(new java.awt.Color(19, 16, 71));
        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Selecionar Tudo", "Educação", "Casa", "Saúde" }));
        jComboBoxCategoria.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBoxCategoria.setMinimumSize(new java.awt.Dimension(108, 22));
        jComboBoxCategoria.setOpaque(true);
        jComboBoxCategoria.setPreferredSize(new java.awt.Dimension(108, 22));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jComboBoxStatus.setForeground(new java.awt.Color(19, 16, 71));
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Todos", "Pagas", "Não Pagas" }));
        jComboBoxStatus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jComboBoxStatus.setMinimumSize(new java.awt.Dimension(108, 22));
        jComboBoxStatus.setOpaque(true);
        jComboBoxStatus.setPreferredSize(new java.awt.Dimension(108, 22));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFiltrosLayout = new javax.swing.GroupLayout(jPanelFiltros);
        jPanelFiltros.setLayout(jPanelFiltrosLayout);
        jPanelFiltrosLayout.setHorizontalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPeríodo)
                    .addComponent(jComboBoxPeríodo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoLançamento, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCategoria)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addComponent(labelStatus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelFiltrosLayout.setVerticalGroup(
            jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelStatus)
                            .addComponent(labelCategoria)
                            .addComponent(labelTipoLançamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelFiltrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxLançamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFiltrosLayout.createSequentialGroup()
                        .addComponent(labelPeríodo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPeríodo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBoxPeríodo.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jPanelFiltros, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 1340, -1));
        jPanelFiltros.getAccessibleContext().setAccessibleName("PainelGraficoPizza");

        labelRelatóriosBlue.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        labelRelatóriosBlue.setForeground(new java.awt.Color(97, 90, 205));
        labelRelatóriosBlue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRelatóriosBlue.setText("Relatórios");
        labelRelatóriosBlue.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(labelRelatóriosBlue, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel6.setText("Despesas ao Longo da Semana");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(265, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jLabel9.setText("Economia de 20%");

        jLabel10.setText("semana passada");

        jLabel11.setText("essa semana");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(21, 21, 21))
        );

        jLabel12.setText("pagas");

        jLabel13.setText("não pagas");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Descrição", "Visualizar"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 396, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleName("PanelGraficoLinha");
        jPanel4.getAccessibleContext().setAccessibleName("PainelGraficoBarra");

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 1400, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonGerarActionPerformed

    private void jComboBoxLançamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLançamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLançamentosActionPerformed

    private void jComboBoxPeríodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPeríodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPeríodoActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed
private void adicionarGraficos() {
        
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Pagas", 60);
        pieDataset.setValue("Não Pagas", 40);

        JFreeChart pieChart = ChartFactory.createPieChart(
            "Categoria das Despesas",
            pieDataset,
            true, true, false
        );

        ChartPanel piePanel = new ChartPanel(pieChart);
        
        piePanel.setPreferredSize(new java.awt.Dimension(jPanelFiltros.getWidth(), jPanelFiltros.getHeight()));
        jPanelFiltros.removeAll();  
        jPanelFiltros.setLayout(new java.awt.BorderLayout());
        jPanelFiltros.add(piePanel, java.awt.BorderLayout.CENTER);
        jPanelFiltros.validate();

        
        DefaultCategoryDataset barDataset = new DefaultCategoryDataset();
        barDataset.setValue(200, "Despesas", "Semana Passada");
        barDataset.setValue(150, "Despesas", "Essa Semana");

        JFreeChart barChart = ChartFactory.createBarChart(
            "Despesas ao Longo da Semana",
            "Semana",
            "Valor (R$)",
            barDataset
        );

        ChartPanel barPanel = new ChartPanel(barChart);
        
        barPanel.setPreferredSize(new java.awt.Dimension(jPanel4.getWidth(), jPanel4.getHeight()));
        jPanel4.removeAll();  
        jPanel4.setLayout(new java.awt.BorderLayout());
        jPanel4.add(barPanel, java.awt.BorderLayout.CENTER);
        jPanel4.validate();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panelicones;
    private javax.swing.JButton jButtonGerar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxLançamentos;
    private javax.swing.JComboBox<String> jComboBoxPeríodo;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNotificação;
    private javax.swing.JLabel jLabelUsuário;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelFiltros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCalculadora;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelLançamentos;
    private javax.swing.JLabel labelPeríodo;
    private javax.swing.JLabel labelPlanejaGo;
    private javax.swing.JLabel labelRelatórios;
    private javax.swing.JLabel labelRelatóriosBlue;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTipoLançamento;
    private javax.swing.JPanel panelNavegação;
    // End of variables declaration//GEN-END:variables
}
